changelog:
  categories:
    - title: New features
      labels:
        - new-feature
    - title: Improvements
      labels:
        - improvement
    - title: Bug fixes
      labels:
        - bugfix
