local composer = require("composer")
native.setProperty("windowMode", "fullscreen")
display.setStatusBar(display.HiddenStatusBar)
math.randomseed(system.getTimer())
composer.gotoScene("Scenes.menu")